github:
  - owner: applidget
    repo: laptop
    labels: ""
    access_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
    webhook_secret: "007"  # TODO(ssaunier): change to environment variable
  - owner: ssaunier
    repo: dotfiles
    labels: ""
    access_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
    webhook_secret: "007"