github:
  - owner: ssaunier
    repo: got_fixed
    labels: ""
    access_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
    webhook_secret: secret
  - owner: ssaunier
    repo: dotfiles
    labels: ""
    access_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
    webhook_secret: secret