github:
  - owner: applidget
    repo: laptop
    labels: ""
    auth_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>
  - owner: ssaunier
    repo: dotfiles
    labels: ""
    auth_token: <%= ENV['GITHUB_PERSONAL_ACCESS_TOKEN'] %>